# Generated by Django 4.2.23 on 2025-09-10 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('seat_book', models.PositiveIntegerField(default=1)),
                ('contribution_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('pickup_location', models.CharField(blank=True, max_length=255, null=True)),
                ('drop_location', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True)),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=12, unique=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('driver', 'Driver'), ('passenger', 'Passenger')], default='passenger', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='carpooling_app.booking')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpooling_app.person')),
            ],
        ),
        migrations.CreateModel(
            name='CreateCarpool',
            fields=[
                ('createcarpool_id', models.AutoField(primary_key=True, serialize=False)),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(max_length=255)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('available_seats', models.IntegerField()),
                ('contribution_per_passenger', models.DecimalField(decimal_places=2, max_digits=10)),
                ('add_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_passenger_allowed', models.PositiveIntegerField()),
                ('contact_info', models.TextField(blank=True, null=True)),
                ('carpool_creator_driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='carpooling_app.person')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='booked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpooling_app.person'),
        ),
        migrations.AddField(
            model_name='booking',
            name='fkCreateCarpool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='carpooling_app.createcarpool'),
        ),
        migrations.AddField(
            model_name='booking',
            name='passenger_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_bookings', to='carpooling_app.person'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('details', models.CharField(max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='carpooling_app.person')),
            ],
        ),
    ]
