# Generated by Django 4.2.23 on 2025-09-10 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='User',
        ),
    ]
