# Generated by Django 4.2.23 on 2025-09-10 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling_app', '0002_rename_person_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='portal_user',
        ),
    ]
