# Generated by Django 4.2.23 on 2025-09-10 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling_app', '0003_rename_user_portal_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='portal_user',
            new_name='User',
        ),
    ]
