# Generated by Django 4.2.23 on 2025-09-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling_app', '0005_booking_updated_at_booking_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='contact_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
