# Generated by Django 4.2.23 on 2025-09-13 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling_app', '0006_booking_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ride_status',
            field=models.CharField(choices=[('upcomming', 'Upcomming'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcomming', max_length=20),
        ),
    ]
