# Generated by Django 4.2.23 on 2025-09-15 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling_app', '0007_booking_ride_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='fkCreateCarpool',
            new_name='carpool_driver_name',
        ),
    ]
