# Generated by Django 4.2.23 on 2025-09-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling_app', '0008_rename_fkcreatecarpool_booking_carpool_driver_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='createcarpool',
            name='approve_booking_request',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
