# Generated by Django 4.2.23 on 2025-09-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling_app', '0009_createcarpool_approve_booking_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createcarpool',
            name='approve_booking_request',
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
