# Generated by Django 4.2.23 on 2025-09-15 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpooling_app', '0010_remove_createcarpool_approve_booking_request_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
